version: '3'

volumes:
  recrutation_excercise_local_postgres_data: {}
  recrutation_excercise_local_postgres_data_backups: {}
  redis-data:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: recrutation_excercise_local_django
    container_name: recrutation_excercise_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: recrutation_excercise_production_postgres
    container_name: recrutation_excercise_local_postgres
    volumes:
      - recrutation_excercise_local_postgres_data:/var/lib/postgresql/data
      - recrutation_excercise_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: recrutation_excercise_local_docs
    container_name: recrutation_excercise_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./recrutation_excercise:/app/recrutation_excercise:z
    ports:
      - "9000:9000"
    command: /start-docs

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    restart: always
    depends_on:
      - django


  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


  # celeryworker:
  #   <<: *django
  #   image: recrutation_excercise_local_celeryworker
  #   container_name: recrutation_excercise_local_celeryworker
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports: []
  #   command: /start-celeryworker

  # celerybeat:
  #   <<: *django
  #   image: recrutation_excercise_local_celerybeat
  #   container_name: recrutation_excercise_local_celerybeat
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports: []
  #   command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: recrutation_excercise_local_flower
  #   container_name: recrutation_excercise_local_flower
  #   ports:
  #     - "5555:5555"
  #   command: /start-flower