# Generated by Django 4.0.9 on 2023-02-26 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='thumbnail_sizes',
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='width',
        ),
        migrations.RemoveField(
            model_name='thumbnailsize',
            name='width',
        ),
        migrations.AddField(
            model_name='thumbnailsize',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_size', to='upload_image.plan'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upload_image.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_image', to='upload_image.profile'),
        ),
    ]
