# Generated by Django 4.0.10 on 2023-03-06 17:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0003_alter_profile_plan_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiration_date', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary_link', to='upload_image.thumbnail')),
            ],
        ),
    ]
